### PR TITLE
adding initial fastlane structure

### PR DESCRIPTION
**Pull request by IzzySoft**
should be helpful for deployment to Google Play (and my updater can fetch changes you make, so they also get reflected [here](https://apt.izzysoft.de/fdroid/index/apk/be.robinj.distrohopper) :wink:)

PS: Should you add more files (e.g. screenshots, or per-release changelogs – see [my cheat-sheet](https://gitlab.com/snippets/1895688) for details), please let me know – so I can tell my updater to fetch them as well.

### CODE REVIEW

**Comment by IzzySoft** [comment]
Anything missing here that keeps this PR from being merged, @RobinJ1995?

**Comment by IzzySoft** [comment]
I hope I don't annoy you with another ping, @RobinJ1995 – but some indicator would be much appreciated. I'd like to clean up my "collection of forks" before losing track :wink: This PR is just adding 4 new files describing your app in a well-established structure. The files are rather small, too, so this should be easy to review. Should something be holding you back, a small note would be nice for clarification. Thanks!

**Comment by RobinJ1995** [comment]
I don't think it helps with deployment to Google Play ("deployment" meaning "I drag and drop an AAB file into the developer console"), but I don't see the harm in having this is if helps keep the entry in your F-Droid repo up-to-date :) Thanks.

**Comment by IzzySoft** [comment]
Thanks for merging! And yes, if you update the description in Fastlane, my updater will fetch that with the next release now.

**Pull request merged**
